/// Flutter icons Navigation
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Navigation
///      fonts:
///       - asset: fonts/Navigation.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Navigation {
  Navigation._();

  static const _kFontFam = 'Navigation';
  static const String? _kFontPkg = null;

  static const IconData lock = IconData(0xf319, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
